const projects = [
  {
    name: 'React Drum Machine',
    heading: 'React Drum Machine',
    info: 'A drum machine built with react',
    demoLink: 'https://aneuhold-drum-machine.netlify.com/',
    codeLink: 'https://github.com/aneuhold/React-Projects/tree/master/fcc-drum-machine',
    thumbnailUrl: 'https://i.imgur.com/Y7N4jRO.png',
    thumbnailDescription: 'React Drum Machine Thumbnail.',
  },
  {
    name: 'React Calculator',
    heading: 'React Calculator',
    info: 'A calculator built with react',
    demoLink: 'https://aneuhold-calculator.netlify.com/',
    codeLink: 'https://github.com/aneuhold/React-Projects/tree/master/fcc-calculator',
    thumbnailUrl: 'https://i.imgur.com/Jn7zDGy.png',
    thumbnailDescription: 'React Cacluator Thumbnail.',
  },
  {
    name: 'React Pomodoro Clock',
    heading: 'React Pomodoro Clock',
    info: 'A pomodoro clock built with react',
    demoLink: 'https://aneuhold-pomodoro-clock.netlify.com/',
    codeLink: 'https://github.com/aneuhold/React-Projects/tree/master/fcc-pomodoro-clock',
    thumbnailUrl: 'https://i.imgur.com/UsnewFM.png',
    thumbnailDescription: 'Pomodoro Clock Thumbnail.',
  },
  {
    name: 'MongoDB Exercise Tracker',
    heading: 'MongoDB Exercise Tracker',
    info: 'Built with node.js and express',
    demoLink: 'https://decisive-cowl.glitch.me/',
    codeLink: 'https://github.com/aneuhold/fcc-exercisetracker',
    thumbnailUrl: 'https://i.imgur.com/Ql5RFLb.png',
    thumbnailDescription: 'MongoDB Exercise Tracker Thumbnail.',
  },
  {
    name: 'URL Shortener',
    heading: 'URL Shortener',
    info: 'Built with node.js, express, and MongoDB',
    demoLink: 'https://tangible-risk.glitch.me/',
    codeLink: 'https://github.com/aneuhold/fcc-urlshortener',
    thumbnailUrl: 'https://i.imgur.com/i2rhDTm.png',
    thumbnailDescription: 'URL Shortener Thumbnail.',
  },
  {
    name: 'BattleShip',
    heading: 'BattleShip',
    info: 'Built in Java as a group project for SER215',
    codeLink: 'https://github.com/aneuhold/ser215-battleship',
    thumbnailUrl: 'https://i.imgur.com/RKV5vQ4.png',
    thumbnailDescription: 'Battleship Thumbnail.',
  },
  {
    name: 'BlackJack',
    heading: 'Command Line BlackJack',
    info: 'Built in Python 3.x',
    demoLink: 'https://repl.it/@aneuhold/BlackJack',
    codeLink: 'https://github.com/aneuhold/python-projects/tree/master/Black%20Jack',
    thumbnailUrl: 'https://i.imgur.com/gE20dr8.png',
    thumbnailDescription: 'Python Command Line BlackJack Thumbnail.',
  },
];

export default projects;
